const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  listPbs: () => ipcRenderer.invoke('pbs:list'),
  sendPbs: (slots) => ipcRenderer.invoke('offer:send', slots),
  listPendingOffers: () => ipcRenderer.invoke('offer:listPending'),
  decideOffer: (id, accept, opts = {}) =>
    ipcRenderer.invoke('offer:decide', { id, accept, ...opts }),
  startPairing: (mode) => ipcRenderer.invoke('pair:start', mode),
  enterPin: (pin) => ipcRenderer.invoke('pair:enterPin', pin),
  initiatePair: (target) => ipcRenderer.invoke('pair:initiate', target),
  probePeer: (target) => ipcRenderer.invoke('peer:probe', target),
  currentPair: () => ipcRenderer.invoke('pair:current'),
  listDiscoveredPeers: () => ipcRenderer.invoke('discovery:list'),
  onDiscoveryPeers: (cb) => ipcRenderer.on('discovery:peers', (_e, d) => cb(d)),
  status: () => ipcRenderer.invoke('status'),
  onPeerStatus: (cb) => ipcRenderer.on('peer:status', (_e, d) => cb(d)),
  onOfferIncoming: (cb) => ipcRenderer.on('offer:incoming', (_e, d) => cb(d)),
  onOfferNeedsRoom: (cb) => ipcRenderer.on('offer:needs-room', (_e, d) => cb(d)),
  onOfferLockBlocked: (cb) => ipcRenderer.on('offer:lock-blocked', (_e, d) => cb(d)),
  onOfferExpired: (cb) => ipcRenderer.on('offer:expired', (_e, d) => cb(d)),
  onPairStatus: (cb) => ipcRenderer.on('pair:status', (_e, d) => cb(d)),
  onSaveChanged: (cb) => ipcRenderer.on('save:changed', () => cb()),
  onShowView: (cb) => ipcRenderer.on('view:show', (_e, d) => cb(d)),
  onReceivedChanged: (cb) => ipcRenderer.on('received:changed', () => cb()),
  onPeersChanged: (cb) => ipcRenderer.on('peers:changed', () => cb()),
  onDeferredChanged: (cb) => ipcRenderer.on('deferred:changed', (_e, d) => cb(d)),
  listReceived: () => ipcRenderer.invoke('received:list'),
  deleteReceived: (slot) => ipcRenderer.invoke('received:delete', slot),
  compareTrack: (trackId) => ipcRenderer.invoke('compare:track', trackId),
  listDeferred: () => ipcRenderer.invoke('deferred:list'),
  settings: {
    get: () => ipcRenderer.invoke('settings:get'),
    pickSavePath: () => ipcRenderer.invoke('settings:pickSavePath'),
    autoDetect: () => ipcRenderer.invoke('settings:autoDetect'),
    forgetPeers: () => ipcRenderer.invoke('settings:forgetPeers'),
    setManualPeer: (addr) => ipcRenderer.invoke('settings:setManualPeer', addr),
    setNickname: (uuid, nickname) => ipcRenderer.invoke('settings:setNickname', uuid, nickname),
    setAutoShare: (enabled) => ipcRenderer.invoke('settings:setAutoShare', enabled),
  },
  update: {
    check: () => ipcRenderer.invoke('update:check'),
    download: () => ipcRenderer.invoke('update:download'),
    install: () => ipcRenderer.invoke('update:install'),
    status: () => ipcRenderer.invoke('update:status'),
    onStatus: (cb) => ipcRenderer.on('update:status', (_e, d) => cb(d)),
    onAutoShareFiring: (cb) => ipcRenderer.on('auto-share:firing', (_e, d) => cb(d)),
  },
  sendPbsTo: (slots, targetUuid) => ipcRenderer.invoke('offer:sendTo', { slots, targetUuid }),
});
